/lifecycle_manager_laser:
  use_preset: "lifecycle_manager.yaml"
  use_if:
    robot_type: ari
    laser_model: ydlidar-tg15
  ros__parameters:
    node_names:
      [
        "pal_laser_filters",
        "direct_laser_odometry",
      ]
