/pal_laser_filters:
  use_preset: "range_filter_w_non_circular_footprint.yaml"
  use_if:
    robot_type: ari
  ros__parameters:
    filter2:
      params:
        footprint: "[[0.1575, 0.2795], [-0.5975, 0.2795], [-0.5975, -0.2795], [0.1575, -0.2795]]"