/torso_front_camera:
  use_preset: "d435i_rgbd_high_accuracy.yaml"
  use_if:
    robot_type: ari
    camera_model: realsense-d435i
  ros__parameters:
    camera_name: "torso_front_rgbd_camera"
    serial_no: "${serial_number_camera_0}"

/torso_back_camera:
  use_preset: "t265_stereo_camera.yaml"
  use_if:
    robot_type: ari
  ros__parameters:
    camera_name: "torso_back_camera"
    serial_no: "${serial_number_camera_1}"