/torso_back_stereo_camera:
  use_preset: "t265_stereo_camera.yaml"
  use_if:
    robot_type: ari
  ros__parameters:
    camera_name: "torso_back_stereo_camera"
    serial_no: "${serial_number_camera_1}"